### ISSUE TITLE
Mealplan List

### ISSUE THREAD

**Issue by incredible-elk** [incredible-elk/capstone-project#1]
## Value statement

As a **user**
I need **one place to keep my meal ideas and recipes**
so that **I have more time to live my life and spend less time thinking about what to cook on a daily basis**

#### Before user input
![final before user input](https://user-images.githubusercontent.com/37314329/86446751-ac8ae200-bd14-11ea-9582-21bbc4dea586.jpg)

#### After user input
![final after user input](https://user-images.githubusercontent.com/37314329/86446765-b1e82c80-bd14-11ea-97f2-c31971b19b8a.jpg)

## Acceptance criteria

- [x] New MealplanList starts with one empty input field (title) and one empty checkbox input
- [x] New checkbox input field is added when clicking on + Add item button
- [x] Input fields can be edited at any time (both checked or unchecked)
- [x] Checked meals stay on the list
- [x] Empty input fields don't get deleted

## Tasks

- [x] Create feature branch
- [x] Create component Meal in Storybook
- [x] Write component tests
- [x] Add component Meal to app and render Meals through MealList component
- [x] Add global styles
- [x] Add missing styles (Header => fixed) 

## Size

medium
