### ISSUE TITLE
Recipe detail page

### ISSUE THREAD

**Issue by incredible-elk** [incredible-elk/capstone-project#11]
## Value statement

As a **user**
I need **to be able to have access to the whole recipe** 
so that **I can write my shoppinglist and have access to the recipe while cooking**

## Description (Text, Scribble, Wireframe, Design)

![Recipe detail](https://user-images.githubusercontent.com/37314329/88213147-a1aed780-cc58-11ea-96d8-a59a5030b070.jpg)

## Acceptance criteria

- [x] Navigate to recipe detail page when recipe title on recipe page is clicked
- [x] Navigate back to recipe page when back arrow is clicked
- [x] Append target recipe id to URL

## Tasks

- [x] Create feature branch
- [x] Create recipe detail component and add to Storybook
- [x] Load recipe details from mock.json
- [x] Add RecipeDetailPage
- [x] Add routing for every recipe
- [x] Add back to recipes arrow to navigate back to the recipes page
- [x] Add cypress test

## Size

medium

**Comment by incredible-elk** [comment]
## Value statement

As a **user**
I need **to be able to have access to the whole recipe** 
so that **I can write my shoppinglist and have access to the recipe while cooking**

## Description (Text, Scribble, Wireframe, Design)

![Recipe detail](https://user-images.githubusercontent.com/37314329/88213147-a1aed780-cc58-11ea-96d8-a59a5030b070.jpg)


## Acceptance criteria

- [ ] Navigate to recipe detail page when recipe title on recipe page is clicked
- [ ] Navigate back to recipe page when back arrow is clicked
- [ ] Display target recipe title in header and append to URL


## Tasks

- [ ] Create feature branch
- [ ] Create recipe detail component and add to Storybook
- [ ] Load recipe details from firebase backend
- [ ] Add recipe title to header
- [ ] Add routing for every recipe
- [ ] Add back to recipes arrow to navigate back to the recipes page
- [ ] Add cypress test


## Size

medium
