### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by incredible-elk** [incredible-elk/capstone-project#4]
## Value statement

As a **user**
I need **to be able to delete items from my mealplan**
so that **I can stay flexible in my planning**

#### Before meal gets deleted
![before delete](https://user-images.githubusercontent.com/37314329/86448564-38057280-bd17-11ea-9605-8d4b5845b17c.jpg)
 
#### After meal got deleted
![after delete](https://user-images.githubusercontent.com/37314329/86448622-48b5e880-bd17-11ea-9eb9-3f0cbc88258a.jpg)

## Acceptance criteria

- [x] Delete icon appears only on the end of the input field in focus
- [x] On click on the delete icon - only the input field that targeted the action gets deleted
- [x] Both titles and checked / unchecked items can be deleted
- [x] Can't undo delete for now

## Tasks

- [x] Create feature branch
- [x] Create Delete Component (including delete icon) in Storybook
- [x] Write tests
- [x] Add component to app
- [x] Add missing styles

## Size

small
