### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by incredible-elk** [incredible-elk/capstone-project#6]
## Value statement

As a **user**
I need **my mealplan to be saved**
so that **I can access it many times over**

## Acceptance criteria

- [x] Auto save any changes to the Mealplan
- [x] Save when an input field detected a change (after focus)
- [x] After refresh load last version from local

## Tasks

- [x] Create feature branch
- [x] Create SaveToLocal and LoadFromLocal functions
- [x] Write tests

## Size

small
