### ISSUE TITLE
Mealplan / Recipe Toggler

### ISSUE THREAD

**Issue by incredible-elk** [incredible-elk/capstone-project#9]
## Value statement

As a **user**
I need **to have my mealplan and favorite recipes in one place** 
so that **I am able to access both wherever I want**

## Description (Text, Scribble, Wireframe, Design)

![Mealplan page](https://user-images.githubusercontent.com/37314329/88207645-66a8a600-cc50-11ea-911c-0586dfdfb203.jpg)

![Recipe page](https://user-images.githubusercontent.com/37314329/88207654-690b0000-cc50-11ea-9be4-2891672c6e57.jpg)

## Acceptance criteria

- [x] Button to navigate between mealplan and recipes is bottom center in a navbar
- [x] Navigate between pages when button is clicked

## Tasks

- [x] Create feature branch
- [x] Create recipe mock json file with min. 4 recipes
- [x] Create MealplanPage
- [x] Create RecipePage
- [x] Create recipe button component and add to Storybook
- [x] Create mealplan button component and add to Storybook
- [x] Create recipe list component and add to Storybook
- [x] Add react router to navigate between the two pages
- [x] Create 404 PageNotFound component and define as route
- [x] Render recipe-mock.json to recipe page
- [x] Add cypress test

## Size

large

**Comment by incredible-elk** [comment]
## Value statement

As a **user**
I need **to have my mealplan and favorite recipes in one place** 
so that **I am able to access both wherever I want**

## Description (Text, Scribble, Wireframe, Design)

![Mealplan page](https://user-images.githubusercontent.com/37314329/88207645-66a8a600-cc50-11ea-911c-0586dfdfb203.jpg)


![Recipe page](https://user-images.githubusercontent.com/37314329/88207654-690b0000-cc50-11ea-9be4-2891672c6e57.jpg)


## Acceptance criteria

- [ ] Button to navigate between mealplan and recipes is bottom center in a navbar
- [ ] Navigate between pages when button is clicked



## Tasks

- [ ] Create feature branch
- [ ] Create recipe mock json file with min. 4 recipes
- [ ] Create recipe button component and add to Storybook
- [ ] Create mealplan button component and add to Storybook
- [ ] Create recipe list component and add to Storybook
- [ ] Add react router to navigate between the two pages
- [ ] Render recipe-mock.json to recipe page
- [ ] Add cypress test


## Size

large
